name: flutter_qvapay_payment
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
